### ISSUE TITLE
Questions regarding setup a Signal Server

### ISSUE THREAD

**Issue by WilliamYuTW** [madeindra/setup-guide#14]
Hi @madeindra, 

Thanks for providing this great setup-guide repo. 

I'm currently learning how to set up my own server and I have a few questions:

- What I'm trying to do is to just have a server to handle the message between devices and I don't need all the other features like AWS and Recaptcha, is that possible?
- Since the server code is written in Java, is it possible to use other languages like erlang to build the server?

I appreciate your help in advance. 

Cheers

**Comment by madeindra** [comment]
Hi @WilliamYuTW,

* I think it's possible but you need to remove the initialization for the AWS, iirc it's on `WhisperServerService.java`. As for recaptcha, it's also removeable but you need to do some modification too.

* Sorry but I havr no idea about that. If you mean you want to rewrite it, you could but isn't better to write a simple chat app rather than rewriting signal? There should be a lot of open source simple chat app you can look into in github, some of them use Firebase too.

**Comment by WilliamYuTW** [comment]
@madeindra Thanks for your reply! I'll give it try.
